# alembic/script.py.mako
"""add matric_num and admission_session

Revision ID: 84264b56dee2
Revises: a19dec4cc1b6
Create Date: 2026-04-18 18:54:04.229514

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84264b56dee2'
down_revision: Union[str, None] = 'a19dec4cc1b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('matric_num', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('admission_session', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_users_matric_num'), 'users', ['matric_num'], unique=True)
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_matric_num'), table_name='users')
    op.drop_column('users', 'admission_session')
    op.drop_column('users', 'matric_num')
    # ### end Alembic commands ###
