"""Strip full S3 URLs from materials.file_url to plain object keys.

Revision ID: 20260607_1600_strip_material_file_urls
Revises: 20260421_0000_a8f3c9d2e1b4_add_notification_tables
Create Date: 2026-06-07 16:00:00.000000

Background
----------
The original StorageService.upload_file() returned a hard-coded AWS S3 URL
regardless of the actual storage backend (even when using MinIO), e.g.:

    https://ams-storage-bucket.s3.amazonaws.com/uploads/<uuid>-filename.pdf

The fixed service now stores only the object key:

    uploads/<uuid>-filename.pdf

This migration scans ``materials.file_url`` for any value that looks like
a full URL (starting with "http") and extracts just the object key portion.

Key extraction strategy
-----------------------
Rather than trying to parse URL structure (which varies between AWS-style
subdomain URLs and path-style MinIO URLs), we locate the first occurrence
of the known key prefix ``uploads/`` inside the URL and take everything
from there. This is reliable because all keys generated by the old
StorageService started with ``uploads/``.

No schema change is required — the column type remains VARCHAR(1000).
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "b3e1f9a72c05"
down_revision = "a8f3c9d2e1b4"
branch_labels = None
depends_on = None


def _extract_key(url: str) -> str:
    """Extract the object key from a full S3/MinIO URL.

    Looks for the first ``uploads/`` segment in the URL and returns
    everything from that point on. This handles both URL styles:

      AWS subdomain-style:
        https://bucket.s3.amazonaws.com/uploads/uuid-file.pdf
        → uploads/uuid-file.pdf

      MinIO path-style:
        http://minio:9000/bucket/uploads/uuid-file.pdf
        → uploads/uuid-file.pdf

    If ``uploads/`` is not found (unexpected format), returns the original
    value unchanged so we never corrupt data silently.
    """
    marker = "uploads/"
    idx = url.find(marker)
    if idx >= 0:
        return url[idx:]
    # Unknown URL format — leave untouched and log for manual review.
    return url


def upgrade() -> None:
    """Convert full S3 URLs in materials.file_url to plain object keys."""
    conn = op.get_bind()

    # Fetch all rows that look like full URLs
    rows = conn.execute(
        sa.text("SELECT id, file_url FROM materials WHERE file_url LIKE 'http%'")
    ).fetchall()

    if not rows:
        print("  → No full-URL file_url values found; nothing to migrate.")
        return

    print(f"  → Migrating {len(rows)} materials.file_url row(s)…")
    for row in rows:
        new_key = _extract_key(row.file_url)
        conn.execute(
            sa.text("UPDATE materials SET file_url = :key WHERE id = :id"),
            {"key": new_key, "id": str(row.id)},
        )
        print(f"    {row.id}: {row.file_url!r} → {new_key!r}")

    print("  ✓ Migration complete.")


def downgrade() -> None:
    """No-op: we cannot reconstruct the original URLs from the object key alone."""
    pass
