# alembic/script.py.mako
"""array_roles

Revision ID: 62bd1310aaef
Revises: 84264b56dee2
Create Date: 2026-04-18 20:43:22.950850

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62bd1310aaef'
down_revision: Union[str, None] = '84264b56dee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roles', sa.ARRAY(sa.String(length=20)), server_default='{}', nullable=False))
    
    # Data migration: Convert single role to array roles
    op.execute("UPDATE users SET roles = ARRAY[role]")
    
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    
    # Data migration: Convert array roles back to single role (take first element)
    op.execute("UPDATE users SET role = roles[1]")
    
    # Set to non-nullable after filling data
    op.alter_column('users', 'role', nullable=False)
    
    op.drop_column('users', 'roles')
    # ### end Alembic commands ###
